router:
  hostname: "Router1"
  interfaces:
    - interface: "GigabitEthernet0/1"
      ip_address: "192.168.1.1"
      subnet_mask: "255.255.255.0"
      description: "Primary interface"
    - interface: "GigabitEthernet0/2"
      ip_address: "192.168.2.1"
      subnet_mask: "255.255.255.0"
      description: "Secondary interface"