---
- name: Get NETCONF data
  hosts: nokia
  gather_facts: no
  connection: netconf
  vars:
    ansible_python_interpreter: /root/.pyenv/shims/python3

  tasks:
    - name: Get data from NETCONF
      ansible.netcommon.netconf_get:
        display: xml
        filter: >
          <configuration>
            <interfaces/>
          </configuration>
      register: netconf_response

    - name: Print NETCONF response
      debug:
        var: netconf_response

    - name: Check Python interpreter
      command: which python3
      register: python_interpreter

    - name: Print Python interpreter
      debug:
      var: python_interpreter.stdout

